-- local lib = require("lib")
-- local merge = lib.merge

-- data:extend({
-- 	{
-- 		type = "recipe",
-- 		name = "_Template-recipe",
-- 		category = "crafting",
-- 		energy_required = 0.5,
-- 		ingredients = {
-- 			{ type = "item", name = "", amount = 1 },
-- 		},
-- 		results = {
-- 			{ type = "item", name = "", amount = 1 },
-- 		},
-- 		hide_from_signal_gui = false,
-- 		auto_recycle = false,
-- 	},

-- 	merge(data.raw.lab["lab"], {
-- 		name = "new-lab",
-- 		max_health = 300,
-- 	}),
-- })
